spring:
    application:
        name: online-book-store
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/book-store?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
        password: ${DB_PASSWORD}
        username: ${DB_USERNAME}
    devtools:
        livereload:
            enabled: true
        restart:
            enabled: true
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
            format_sql: true
    sql:
        init:
            mode: never
    mvc:
        hidden method:
            filter:
                enabled: true
    servlet:
        multipart:
            enabled: true
            max-file-size: 5MB
            max-request-size: 5MB
    web:
        resources:
            static-locations: file:src/main/resources/static/
            cache:
                period: 0
    thymeleaf: # Thymeleaf
        cache: false
        mode: HTML
        encoding: UTF-8
        prefix: file:src/main/resources/templates/
logging:
    level:
        org.hibernate.SQL: debug
        org.hibernate.orm.jdbc.bind: trace
#        org.springframework: debug
server:
  tomcat:
      max-swallow-size: 5MB

cloudinary:
    name: ${CLOUDINARY_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}